# Generated by Django 3.1.6 on 2021-02-08 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20210207_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_author', to='p_library.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='friend_take',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taked', to='p_library.friend', verbose_name='Книга у '),
        ),
        migrations.AlterField(
            model_name='friend',
            name='e_mail',
            field=models.EmailField(max_length=50, verbose_name='Эл.почта'),
        ),
    ]
