# Generated by Django 2.2.6 on 2021-02-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_book_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Загрузите изображение'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pub_name',
            field=models.TextField(verbose_name='Название издательства'),
        ),
    ]
